"""upgrade otdel data

Revision ID: 2214e7e5301b
Revises: 0b1dd4eb9069
Create Date: 2020-03-14 10:51:09.646503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2214e7e5301b'
down_revision = '0b1dd4eb9069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_otdel', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_otdel', 'user', ['otdel'], unique=1)
    # ### end Alembic commands ###
