"""del table, add data

Revision ID: decdf519fcc7
Revises: e59cc366a7d3
Create Date: 2020-03-20 19:59:59.579351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decdf519fcc7'
down_revision = 'e59cc366a7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_answers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('question', sa.VARCHAR(length=500), nullable=True),
    sa.Column('answer', sa.VARCHAR(length=500), nullable=True),
    sa.Column('user_answer', sa.VARCHAR(length=500), nullable=True),
    sa.Column('result', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
