"""add seed, answer in User

Revision ID: e59cc366a7d3
Revises: b47d7e19b467
Create Date: 2020-03-19 19:41:43.112209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59cc366a7d3'
down_revision = 'b47d7e19b467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('answers', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('seed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'seed')
    op.drop_column('user', 'answers')
    # ### end Alembic commands ###
